### ISSUE TITLE
About the CTC implementation 

### ISSUE THREAD

**Issue by ybai-nlp** [FLC777/GLAT#1]
Hi, thanks for your brilliant work! 

I have read your paper and want to reproduce the results of GLAT model with CTC loss.

However, I noticed that there is no implementation of the proposed glancing training with CTC loss, where you use LCS distance between the Y and Y^.

I had some trouble of implementing this (mainly the selection of Y and the LCS calculation for tensors) and I am wondering whether you could kindly release this part of the code. 

Thanks a lot!

**Comment by zkx06111** [comment]
Same here.
Also, I wonder if the authors are using CTC loss or Cross Entropy loss for GLAT + CTC. By cross entropy loss, I mean that calculating the cross entropy loss for the best alignment.

**Comment by SirRob1997** [comment]
Would also appreciate an implementation, for now, I'll give it a shot to implement it myself!
