### ISSUE TITLE
Inference with NPD. Issue: AttributeError: 'dict' object has no attribute '_get_node_flag'

### ISSUE THREAD

**Issue by chuanmingliu** [FLC777/GLAT#14]
hi, folks

I triggered an issue,

![image](https://user-images.githubusercontent.com/1910024/148668664-c97677ec-c38d-45e5-a584-d6448e83e76a.png)

when I tried to set '--iter-decode-with-external-reranker \' and '--path [checkpoints/nat.pt:at_checkpoints/at.pt]([url](url)) \'

, do inference with NPD.

Did you meet similar issues,

and do you have any ideas?

It could help me a lot.

Thanks.

**Comment by jiqimaoke** [comment]
hi, folks, how did you solve this problem finally? I meet the same issue right now. Thank you very much.
