### ISSUE TITLE
  About Data Set Selection

### ISSUE THREAD

**Issue by Yonghao-Li** [FLC777/GLAT#17]
Hello, author, while reviewing your code, I found that you did not specify which dataset to use. I read your paper, such as WMT4en de, and downloaded it. However, as for the src dict and tgt dict parameters in preprocess.py, I did not find dict.en.txt and dict.de.txt in the dataset. I dare to bother you, but I hope you can provide a dataset.

**Comment by FLC777** [comment]
You can download the data from fairseq: https://github.com/facebookresearch/fairseq/tree/main/examples/nonautoregressive_translation, or from mask-predict: https://github.com/facebookresearch/Mask-Predict. You do not need to specify the dict file as the preprocess code will generate the dict file first and preprocess the data with the generated dict.
