### ISSUE TITLE
about mask_id in "glat_ctc.py" 41 line

### ISSUE THREAD

**Issue by thunder123321** [FLC777/GLAT#18]
I noticed that the blank_id used in the generator file and ctc_loss is unk_idx=3, why use "pad_id=1" as the masked_id in the "get_align_target" function in the "glat_ctc.py" file, this should be blank_id.

**Comment by FLC777** [comment]
Thank you for pointing out the inconsistency. The blank_id should be the same. And the code has also been updated.
